version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: zeze-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: projectzeze
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: projectzeze
    ports:
      - 3307:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
