POST http://localhost:8080/api/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test-image.png"

< ../test-image.png
--WebAppBoundary--
