# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Development Server Deployment

on:
  workflow_dispatch:

env:
  BUCKET: 'slidemd-build'
  LATEST: 'latest'
  BACKUP: 'backup'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Check S3
        uses: tuler/s3-check-action@master
        id: check_S3
        env:
          FILE: back/${{ env.LATEST }}.jar
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: ${{ env.BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create back up build
        if: steps.check_S3.outputs.exists == 'true'
        run: aws s3 mv s3://${BUCKET}/dev/back/${LATEST}.jar s3://${BUCKET}/dev/back/${BACKUP}.jar
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/*.jar s3://${BUCKET}/dev/back/${LATEST}.jar --acl public-read-write
